### ISSUE TITLE
Tree Swing

### ISSUE THREAD

**Issue by lukehinds** [stacklok/Demo-repo-Go#1]
**Customer outcome**
A tree swing for pleasure.

**Summary**
A tree swing provides the ability to swing back and forth in a safe and pleasent manner. 

**Link to Product Requirements**
[Link to product requirements document]

**Design Documents**
[Link to design document]

**Related Tasks/Acceptance Criteria**
- [ ] As a user I would like to position myself into a seat with my feet placed on the ground 
- [ ] As a user I wish to self propel myself forwards to start a swinging motion
- [ ] As a user the swing will allow me to swing forwards and backwards, where I can use my body to propel the motion
- [ ] As a user, I would like to come naturally to a stop so that I can disembark safely from the swing.

**Implementation Tasks**

**backend:**
- [ ] #2
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #12
 
**frontend:**
- [ ] #8
- [ ] #9

**data-science:**
- [ ] Ingest swing user data
